version: '3.8'

services:

    db:
      image: postgres:15
      container_name: api_db
      restart: always
      env_file:
        - .env
      mem_limit: 3Gb
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

    redis:
      image: redis:7.0.11-alpine

    api:
      
      build: .
      
      ports:
        - 8000:8000
      expose:
        - 8000
      depends_on:
        - redis
        - db
      env_file:
        - .env
      
      volumes:
        - .:/app
      
      
    flower:
      image: mher/flower
      container_name: flower
      restart: always
      depends_on:
        - redis
      ports:
        - "5555:5555"  # Interface web do Flower
      expose:
        - 5555
      environment:
        - CELERY_BROKER_URL=redis://redis:6379/0
      command: ["celery", "flower", "--broker=redis://redis:6379/0"]


volumes:
  postgres_data:

